import Head from "next/head";
import Image from "next/image";
import Banner from "../Components/Banner/Banner";
import Header from "../Components/Header/Header";
import styles from "../styles/Home.module.css";
import Marquee from "react-fast-marquee";
import About from "../Components/About/About";
import DigitalExp from "../Components/DigitalExp/DigitalExp";
import RoadMap from "../Components/RoadMap/RoadMap";
import Apt from "../Components/Apt/Apt";
import { Grid } from "@mui/material";
import TeamMember from "../Components/TeamMember/TeamMember";
import { Box } from "@mui/system";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Banner />
      <Marquee
        speed={40}
        style={{
          // padding: "5px 0",
          background:
            "linear-gradient(90deg, #028DE4 0%, #F31977 49.14%, #AA09C5 100%)",
        }}
      >
        <ul
          style={{
            display: "flex",
            color: "#fff",
            listStyle: "none",
            justifyContent: "space-around",
          }}
        >
          <li className={styles.list}> MINTING MARCH </li>
          <li className={styles.list}> MINTING MARCH </li>
          <li className={styles.list}> MINTING MARCH </li>
          <li className={styles.list}> MINTING MARCH </li>
          <li className={styles.list}> MINTING MARCH </li>
          <li className={styles.list}> MINTING MARCH </li>
          <li className={styles.list}> MINTING MARCH </li>
          <li className={styles.list}> MINTING MARCH </li>
          <li className={styles.list}> MINTING MARCH </li>
          <li className={styles.list}> MINTING MARCH </li>
          <li className={styles.list}> MINTING MARCH </li>
          <li className={styles.list}> MINTING MARCH </li>
        </ul>
      </Marquee>
      <About />
      <DigitalExp />
      <RoadMap />
      <Grid container sx={{ padding: "0 20px" }} spacing={3}>
        <Apt />
        <Apt />
        <Apt />
        <Apt />
        <Apt />
        <Apt />
      </Grid>
      <Box className="container">
        <Grid container sx={{ padding: "0 20px" }} spacing={3}>
          <TeamMember />
          <TeamMember />
          <TeamMember />
          <TeamMember />
        </Grid>
      </Box>
      {/* <main className={styles.main}></main> */}

      <footer className={styles.footer}>
        {/* <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a> */}
      </footer>
    </div>
  );
}
